/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArmazemRouteImport } from './routes/armazem'
import { Route as IndexRouteImport } from './routes/index'

const ArmazemRoute = ArmazemRouteImport.update({
  id: '/armazem',
  path: '/armazem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/armazem': typeof ArmazemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/armazem': typeof ArmazemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/armazem': typeof ArmazemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/armazem'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/armazem'
  id: '__root__' | '/' | '/armazem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArmazemRoute: typeof ArmazemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/armazem': {
      id: '/armazem'
      path: '/armazem'
      fullPath: '/armazem'
      preLoaderRoute: typeof ArmazemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArmazemRoute: ArmazemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
